version: '3.8'

services:
  web:
    build: .
    ports:
      - "5500:5500"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/app/config/db

volumes:
  mongo-data: